steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_REPOSITORY/quiz-app-backend:$SHORT_SHA'
      - '.'
    
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_REPOSITORY/quiz-app-backend:$SHORT_SHA'
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'quiz-app-backend'
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_REPOSITORY/quiz-app-backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _REPOSITORY: cloud-run-source-deploy

images:
  - '$_AR_HOSTNAME/$PROJECT_ID/$_REPOSITORY/quiz-app-backend:$SHORT_SHA'