steps:
  # Debugging Step: Output substitution variables (optional, useful for verification)
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo AR_HOSTNAME: $_AR_HOSTNAME, PROJECT_ID: $PROJECT_ID, REPOSITORY: $_REPOSITORY, SHORT_SHA: $SHORT_SHA'

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/neat-library-437612-v7/cloud-run-source-deploy/infrastructure-delivery-pipeline/quiz-app-backend:test-build'
      - '.'

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/neat-library-437612-v7/cloud-run-source-deploy/infrastructure-delivery-pipeline/quiz-app-backend:test-build'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'quiz-app-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/neat-library-437612-v7/cloud-run-source-deploy/infrastructure-delivery-pipeline/quiz-app-backend:test-build'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _REPOSITORY: cloud-run-source-deploy/infrastructure-delivery-pipeline

images:
  - 'us-central1-docker.pkg.dev/neat-library-437612-v7/cloud-run-source-deploy/infrastructure-delivery-pipeline/quiz-app-backend:$SHORT_SHA'
