name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Update package-lock.json
        run: npm install
          
      - name: Run tests
        run: npm test
        env:
          CI: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        run: |
          docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/quiz-app-repo/$IMAGE_NAME:${{ github.sha }} .
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/quiz-app-repo/$IMAGE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          REGION: us-central1
        run: |
          gcloud run deploy $IMAGE_NAME \
            --image us-central1-docker.pkg.dev/$PROJECT_ID/quiz-app-repo/$IMAGE_NAME:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated